version: "3.1"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - maria-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: my-bank
      MARIADB_USER: user
      MARIADB_PASSWORD: userpw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  # operation-handler-ui:
  #   build:
  #     context: ./operation-handler-ui
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   container_name: operation-handler-ui
  #   stdin_open: true
  #   volumes:
  #     - ./operation-handler-ui:/app
  #     - /app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=my-bank-cluster
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data:rw

volumes:
  maria-db:
  elasticsearch:
