version: "3.1"

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - maria-db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: rootpw
      MARIADB_DATABASE: my-bank
      MARIADB_USER: user
      MARIADB_PASSWORD: userpw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=CLIENT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES= 1300000000
      - KAFKA_CFG_MAX_REQUEST_SIZE= 1300000000
    depends_on:
      - zookeeper

  operation-handler-ui:
    build:
      context: ./operation-handler-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: operation-handler-ui
    stdin_open: true
    volumes:
      - ./operation-handler-ui:/app
      - /app/node_modules

  my-bank:
    container_name: my-bank
    build:
      context: ./my-bank
      dockerfile: Dockerfile
    image: my-bank:latest
    ports:
      - 8081:8081
    depends_on:
      - mariadb
      - kafka

  operation-handler:
    container_name: operation-handler
    build:
      context: ./operation-handler
      dockerfile: Dockerfile
    image: operation-handler:latest
    ports:
      - 8082:8082
    depends_on:
      - kafka

volumes:
  maria-db:
